services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENV=production
      - LOG_LEVEL=info
    networks:
      - app_network
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload

networks:
  app_network:
    external: true
